/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Preventivi.java
 *
 * Created on 10-giu-2009, 22.33.09
 */
package it.seerp.Gui.Menu;

import configurazioni.CommandInterface;
import it.seerp.Gui.GestioneServizi.GestioneServizi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Andrea
 */
public class MenuServizi extends javax.swing.JPanel implements ActionListener {

    GestioneServizi pannello = null;

    /** Creates new form Preventivi */
    public MenuServizi() {
        initComponents();
    }

    public void setPannello(GestioneServizi pannello) {

        this.pannello = pannello;
        pannello.setMenu(this);
        this.modificaButtonServizi1.setAreaServizi(pannello);
        this.aggiungiButtonServizi1.setServizi(pannello);
        this.eiminaButtonServizi1.setAreaServ(pannello);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aggiungiButtonServizi1 = new it.seerp.Gui.Menu.AggiungiButtonServizi(this);
        eiminaButtonServizi1 = new it.seerp.Gui.Menu.EiminaButtonServizi(this);
        modificaButtonServizi1 = new it.seerp.Gui.Menu.ModificaButtonServizi(this);

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servizi", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_BOTTOM));

        aggiungiButtonServizi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/seerp/icone/32x32/shopping_cart_down.png"))); // NOI18N
        aggiungiButtonServizi1.setToolTipText("Aggiungi");
        aggiungiButtonServizi1.setName("aggiungiButtonServizi1"); // NOI18N
        aggiungiButtonServizi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiButtonServizi1ActionPerformed(evt);
            }
        });

        eiminaButtonServizi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/seerp/icone/32x32/shopping_cart_remove.png"))); // NOI18N
        eiminaButtonServizi1.setToolTipText("Elimina");
        eiminaButtonServizi1.setName("eiminaButtonServizi1"); // NOI18N
        eiminaButtonServizi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eiminaButtonServizi1ActionPerformed(evt);
            }
        });

        modificaButtonServizi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/seerp/icone/32x32/application_edit.png"))); // NOI18N
        modificaButtonServizi1.setToolTipText("Modifica");
        modificaButtonServizi1.setName("modificaButtonServizi1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aggiungiButtonServizi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eiminaButtonServizi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificaButtonServizi1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(modificaButtonServizi1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eiminaButtonServizi1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aggiungiButtonServizi1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eiminaButtonServizi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eiminaButtonServizi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eiminaButtonServizi1ActionPerformed

    private void aggiungiButtonServizi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiButtonServizi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aggiungiButtonServizi1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private it.seerp.Gui.Menu.AggiungiButtonServizi aggiungiButtonServizi1;
    private it.seerp.Gui.Menu.EiminaButtonServizi eiminaButtonServizi1;
    private it.seerp.Gui.Menu.ModificaButtonServizi modificaButtonServizi1;
    // End of variables declaration//GEN-END:variables



        public JButton getModifica() {
        return modificaButtonServizi1;
    }

    public JButton getAggiungi() {
        return aggiungiButtonServizi1;
    }
    public void actionPerformed(ActionEvent e) {
        CommandInterface cmd = (CommandInterface) e.getSource();
        cmd.execute();
    }
}
