/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GestioneUtentiPanel.java
 *
 * Created on 28-mag-2009, 14.54.36
 */

package it.seerp.Menu;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Andrea
 */
public class GestioneUtentiPanel extends javax.swing.JPanel implements ActionListener {

    /** Creates new form GestioneUtentiPanel */
    public GestioneUtentiPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AggiungiUtente = new javax.swing.JButton();
        BottoneEliminaUtenti = new javax.swing.JButton();
        BottoneElencaUtenti = new javax.swing.JButton();
        BottoneModificaUtenti = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestione", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_BOTTOM));
        setToolTipText("Gestione");

        AggiungiUtente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/seerp/icone/32x32/user_add.png"))); // NOI18N
        AggiungiUtente.setToolTipText("Aggiungi");
        AggiungiUtente.setBorder(null);
        AggiungiUtente.setContentAreaFilled(false);
        AggiungiUtente.setHideActionText(true);
        AggiungiUtente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AggiungiUtente.setName("AggiungiUtente"); // NOI18N
        AggiungiUtente.setRequestFocusEnabled(false);
        AggiungiUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggiungiUtenteActionPerformed(evt);
            }
        });

        BottoneEliminaUtenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/seerp/icone/32x32/user_remove.png"))); // NOI18N
        BottoneEliminaUtenti.setToolTipText("Rimuovi");
        BottoneEliminaUtenti.setBorder(null);
        BottoneEliminaUtenti.setContentAreaFilled(false);
        BottoneEliminaUtenti.setHideActionText(true);
        BottoneEliminaUtenti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BottoneEliminaUtenti.setName("BottoneEliminaUtenti"); // NOI18N
        BottoneEliminaUtenti.setRequestFocusEnabled(false);

        BottoneElencaUtenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/seerp/icone/32x32/users.png"))); // NOI18N
        BottoneElencaUtenti.setToolTipText("Elenca");
        BottoneElencaUtenti.setBorder(null);
        BottoneElencaUtenti.setContentAreaFilled(false);
        BottoneElencaUtenti.setHideActionText(true);
        BottoneElencaUtenti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BottoneElencaUtenti.setName("BottoneElencaUtenti"); // NOI18N
        BottoneElencaUtenti.setRequestFocusEnabled(false);

        BottoneModificaUtenti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/seerp/icone/32x32/window_edit.png"))); // NOI18N
        BottoneModificaUtenti.setToolTipText("Modifica");
        BottoneModificaUtenti.setBorder(null);
        BottoneModificaUtenti.setContentAreaFilled(false);
        BottoneModificaUtenti.setHideActionText(true);
        BottoneModificaUtenti.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BottoneModificaUtenti.setName("BottoneModificaUtenti"); // NOI18N
        BottoneModificaUtenti.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AggiungiUtente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BottoneElencaUtenti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BottoneEliminaUtenti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottoneModificaUtenti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BottoneModificaUtenti)
                    .addComponent(AggiungiUtente)
                    .addComponent(BottoneElencaUtenti)
                    .addComponent(BottoneEliminaUtenti))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AggiungiUtente.addActionListener(this);
        BottoneEliminaUtenti.addActionListener(this);
        BottoneElencaUtenti.addActionListener(this);
        BottoneModificaUtenti.addActionListener(this);
    }// </editor-fold>//GEN-END:initComponents

    private void AggiungiUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggiungiUtenteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_AggiungiUtenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggiungiUtente;
    private javax.swing.JButton BottoneElencaUtenti;
    private javax.swing.JButton BottoneEliminaUtenti;
    private javax.swing.JButton BottoneModificaUtenti;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
