/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pannelloPrva.java
 *
 * Created on 3-giu-2009, 8.38.04
 */

package it.seerp.Gui.panel;

import it.seerp.Gui.frame.ObservervableJTabbedPanel;

/**
 *
 * @author Andrea
 */
public class pannelloPrva extends javax.swing.JPanel {
    ObservervableJTabbedPanel pippo;

    public pannelloPrva(   ObservervableJTabbedPanel pluto) {
        this.pippo=pluto;
       
        initComponents();
        
    }

    /** Creates new form pannelloPrva */
    public pannelloPrva() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 51));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
