
package it.seerp.Gui.Gestione.Init;

import it.seerp.Gui.configurazioni.pattern.command.CommandInterface;
import it.seerp.application.Exception.ValidatorException;
import it.seerp.application.applicazione.AppInit;
import it.seerp.application.bean.BeanGuiAmministratore;
import it.seerp.application.bean.BeanGuiAzienda;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Luisa-Andrea
 */
public class GestioneInit extends javax.swing.JPanel {

    BeanGuiAmministratore amm;
    BeanGuiAzienda az;
    private String tipoOP;


    /** Creates new form GestioneInit */
    public GestioneInit() {
        initComponents();
        this.amm = new BeanGuiAmministratore(this);
        this.az = new BeanGuiAzienda(this);
        legameBeans();
        JFrame f = new JFrame();
        f.getContentPane().add(this);
        f.setSize(800, 600);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
        //editabile(true);
    }
        /**
     *
         * qusto metodo permette di modifaicare i campi del form.
         * @ flag che permette di modificare i campi presenti sul form.
     */
    public void editabile(boolean flag) {
        txt_nome.setEnabled(flag);
        txt_cogn.setEnabled(flag);
        txt_cit.setEnabled(flag);
        txt_prov.setEnabled(flag);
        txt_cap.setEnabled(flag);
        txt_codfisc.setEnabled(flag);
        txt_email.setEnabled(flag);
        txt_pwd.setEnabled(flag);
        txt_tel.setEnabled(flag);
        txt_user.setEnabled(flag);
        txt_note.setEnabled(flag);
        txt_ind.setEnabled(flag);

        txt_ragsoc_az.setEnabled(flag);
        txt_cit_az.setEnabled(flag);
        txt_mail_az.setEnabled(flag);
        txt_naz_az.setEnabled(flag);
        txt_ind_az.setEnabled(flag);
        txt_tel_az.setEnabled(flag);
        txt_fax_az.setEnabled(flag);
        txt_piva_az.setEnabled(flag);
        
        
    }

    /**
     *
     * Questo metodo permette di inizzalizzare  i componenti del form.
     * @ s sringa che permette l'inalizzazione, inizializza tutti i campi sul form.
     */
    public void inizializza(String s) {
        txt_nome.setText(s);
        txt_cogn.setText(s);
        txt_cit.setText(s);
        txt_prov.setText(s);
        txt_cap.setText(s);
        txt_codfisc.setText(s);
        txt_email.setText(s);
        txt_pwd.setText(s);
        txt_tel.setText(s);
        txt_user.setText(s);
        txt_note.setText(s);
        txt_note.setText(s);

        txt_ragsoc_az.setText(s);
        txt_cit_az.setText(s);
        txt_mail_az.setText(s);
        txt_naz_az.setText(s);
        txt_ind_az.setText(s);
        txt_tel_az.setText(s);
        txt_fax_az.setText(s);
        txt_piva_az.setText(s);

    }

    /**
     *
     */
    public void legameBeans() {

        amm.setNome(txt_nome);
        amm.setCognome(txt_cogn);
        amm.setTxtCitta(txt_cit);
        amm.setTxtProvincia(txt_prov);
        amm.setCap(txt_cap);
        amm.setCodiceFiscale(txt_codfisc);
        amm.setTipo(new JTextField("personale"));
        amm.setTxtEmail(txt_email);
        amm.setTxtTelefono(txt_tel);
        amm.setTxtUsername(txt_user);
        amm.setTxtPassword(txt_pwd);
        amm.setTxtNote(txt_note);
        amm.setIndirizzo(txt_ind);
        az.setCitta(txt_cit_az);
        az.setEmail(txt_mail_az);
        az.setFax(txt_fax_az);
        az.setInidirizzo(txt_ind_az);
        az.setNazione(txt_naz_az);
        az.setPIVA(txt_piva_az);
        az.setRagioneSociale(txt_ragsoc_az);
        az.setTelefono(txt_tel_az);
        amm.setAzienda(az);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome = new javax.swing.JPanel();
        txt_nome = new javax.swing.JTextField();
        Cognome = new javax.swing.JPanel();
        txt_cogn = new javax.swing.JTextField();
        citta = new javax.swing.JPanel();
        txt_cit = new javax.swing.JTextField();
        provincia = new javax.swing.JPanel();
        txt_prov = new javax.swing.JTextField();
        cap = new javax.swing.JPanel();
        txt_cap = new javax.swing.JTextField();
        cf = new javax.swing.JPanel();
        txt_codfisc = new javax.swing.JTextField();
        email = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        telefono = new javax.swing.JPanel();
        txt_pwd = new javax.swing.JTextField();
        username = new javax.swing.JPanel();
        txt_tel = new javax.swing.JTextField();
        password = new javax.swing.JPanel();
        txt_user = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_note = new javax.swing.JTextArea();
        cittaAzienda = new javax.swing.JPanel();
        txt_cit_az = new javax.swing.JTextField();
        EmailAzienda = new javax.swing.JPanel();
        txt_mail_az = new javax.swing.JTextField();
        faxAz = new javax.swing.JPanel();
        txt_fax_az = new javax.swing.JTextField();
        IndirizzoAz = new javax.swing.JPanel();
        txt_ind_az = new javax.swing.JTextField();
        pivaAz = new javax.swing.JPanel();
        txt_piva_az = new javax.swing.JTextField();
        note8 = new javax.swing.JPanel();
        txt_ragsoc_az = new javax.swing.JTextField();
        note9 = new javax.swing.JPanel();
        txt_tel_az = new javax.swing.JTextField();
        nazioneAz = new javax.swing.JPanel();
        txt_naz_az = new javax.swing.JTextField();
        buttonSalva1 = new it.seerp.Gui.Gestione.BottoniGenerici.ButtonSalva();
        buttonAnnulla1 = new it.seerp.Gui.Gestione.BottoniGenerici.ButtonAnnulla();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        IndirizzoAz1 = new javax.swing.JPanel();
        txt_ind = new javax.swing.JTextField();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();

        setBackground(new java.awt.Color(153, 0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setName("jPanel1"); // NOI18N

        nome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        nome.setName("nome"); // NOI18N

        txt_nome.setFocusCycleRoot(true);
        txt_nome.setName("txt_nome"); // NOI18N
        txt_nome.setNextFocusableComponent(txt_cogn);
        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nomeLayout = new javax.swing.GroupLayout(nome);
        nome.setLayout(nomeLayout);
        nomeLayout.setHorizontalGroup(
            nomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nomeLayout.setVerticalGroup(
            nomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomeLayout.createSequentialGroup()
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cognome.setBorder(javax.swing.BorderFactory.createTitledBorder("Cognome"));
        Cognome.setName("Cognome"); // NOI18N

        txt_cogn.setFocusCycleRoot(true);
        txt_cogn.setName("txt_cogn"); // NOI18N
        txt_cogn.setNextFocusableComponent(txt_codfisc);
        txt_cogn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cognActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CognomeLayout = new javax.swing.GroupLayout(Cognome);
        Cognome.setLayout(CognomeLayout);
        CognomeLayout.setHorizontalGroup(
            CognomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CognomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_cogn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CognomeLayout.setVerticalGroup(
            CognomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CognomeLayout.createSequentialGroup()
                .addComponent(txt_cogn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        citta.setBorder(javax.swing.BorderFactory.createTitledBorder("Città"));
        citta.setName("citta"); // NOI18N

        txt_cit.setFocusCycleRoot(true);
        txt_cit.setName("txt_cit"); // NOI18N
        txt_cit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_citActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cittaLayout = new javax.swing.GroupLayout(citta);
        citta.setLayout(cittaLayout);
        cittaLayout.setHorizontalGroup(
            cittaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cittaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_cit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cittaLayout.setVerticalGroup(
            cittaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cittaLayout.createSequentialGroup()
                .addComponent(txt_cit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        provincia.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincia"));
        provincia.setMaximumSize(new java.awt.Dimension(136, 58));
        provincia.setMinimumSize(new java.awt.Dimension(136, 58));
        provincia.setName("provincia"); // NOI18N

        txt_prov.setFocusCycleRoot(true);
        txt_prov.setName("txt_prov"); // NOI18N
        txt_prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_provActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout provinciaLayout = new javax.swing.GroupLayout(provincia);
        provincia.setLayout(provinciaLayout);
        provinciaLayout.setHorizontalGroup(
            provinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provinciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        provinciaLayout.setVerticalGroup(
            provinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provinciaLayout.createSequentialGroup()
                .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        cap.setBorder(javax.swing.BorderFactory.createTitledBorder("CAP"));
        cap.setName("cap"); // NOI18N

        txt_cap.setFocusCycleRoot(true);
        txt_cap.setName("txt_cap"); // NOI18N
        txt_cap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_capActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout capLayout = new javax.swing.GroupLayout(cap);
        cap.setLayout(capLayout);
        capLayout.setHorizontalGroup(
            capLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_cap, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        capLayout.setVerticalGroup(
            capLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(capLayout.createSequentialGroup()
                .addComponent(txt_cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cf.setBorder(javax.swing.BorderFactory.createTitledBorder("Codice Fiscale"));
        cf.setName("cf"); // NOI18N

        txt_codfisc.setFocusCycleRoot(true);
        txt_codfisc.setName("txt_codfisc"); // NOI18N
        txt_codfisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codfiscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cfLayout = new javax.swing.GroupLayout(cf);
        cf.setLayout(cfLayout);
        cfLayout.setHorizontalGroup(
            cfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_codfisc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cfLayout.setVerticalGroup(
            cfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cfLayout.createSequentialGroup()
                .addComponent(txt_codfisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        email.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        email.setName("email"); // NOI18N

        txt_email.setFocusCycleRoot(true);
        txt_email.setName("txt_email"); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emailLayout = new javax.swing.GroupLayout(email);
        email.setLayout(emailLayout);
        emailLayout.setHorizontalGroup(
            emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emailLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        emailLayout.setVerticalGroup(
            emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailLayout.createSequentialGroup()
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        telefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Password"));
        telefono.setName("telefono"); // NOI18N

        txt_pwd.setFocusCycleRoot(true);
        txt_pwd.setName("txt_pwd"); // NOI18N
        txt_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telefonoLayout = new javax.swing.GroupLayout(telefono);
        telefono.setLayout(telefonoLayout);
        telefonoLayout.setHorizontalGroup(
            telefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telefonoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        telefonoLayout.setVerticalGroup(
            telefonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telefonoLayout.createSequentialGroup()
                .addComponent(txt_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        username.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));
        username.setName("username"); // NOI18N

        txt_tel.setFocusCycleRoot(true);
        txt_tel.setName("txt_tel"); // NOI18N
        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usernameLayout = new javax.swing.GroupLayout(username);
        username.setLayout(usernameLayout);
        usernameLayout.setHorizontalGroup(
            usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usernameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        usernameLayout.setVerticalGroup(
            usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernameLayout.createSequentialGroup()
                .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        password.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        password.setName("password"); // NOI18N

        txt_user.setFocusCycleRoot(true);
        txt_user.setName("txt_user"); // NOI18N
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passwordLayout = new javax.swing.GroupLayout(password);
        password.setLayout(passwordLayout);
        passwordLayout.setHorizontalGroup(
            passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        passwordLayout.setVerticalGroup(
            passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordLayout.createSequentialGroup()
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Note"));
        jPanel2.setName("Note"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txt_note.setColumns(20);
        txt_note.setRows(5);
        txt_note.setName("txt_note"); // NOI18N
        jScrollPane1.setViewportView(txt_note);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cittaAzienda.setBorder(javax.swing.BorderFactory.createTitledBorder("Città"));
        cittaAzienda.setName("cittaAzienda"); // NOI18N

        txt_cit_az.setFocusCycleRoot(true);
        txt_cit_az.setName("txt_cit_az"); // NOI18N
        txt_cit_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cit_azActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cittaAziendaLayout = new javax.swing.GroupLayout(cittaAzienda);
        cittaAzienda.setLayout(cittaAziendaLayout);
        cittaAziendaLayout.setHorizontalGroup(
            cittaAziendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cittaAziendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_cit_az, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cittaAziendaLayout.setVerticalGroup(
            cittaAziendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cittaAziendaLayout.createSequentialGroup()
                .addComponent(txt_cit_az, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EmailAzienda.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));
        EmailAzienda.setName("EmailAzienda"); // NOI18N

        txt_mail_az.setFocusCycleRoot(true);
        txt_mail_az.setName("txt_mail_az"); // NOI18N
        txt_mail_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mail_azActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmailAziendaLayout = new javax.swing.GroupLayout(EmailAzienda);
        EmailAzienda.setLayout(EmailAziendaLayout);
        EmailAziendaLayout.setHorizontalGroup(
            EmailAziendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmailAziendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_mail_az, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        EmailAziendaLayout.setVerticalGroup(
            EmailAziendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmailAziendaLayout.createSequentialGroup()
                .addComponent(txt_mail_az, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        faxAz.setBorder(javax.swing.BorderFactory.createTitledBorder("FAX"));
        faxAz.setName("faxAz"); // NOI18N

        txt_fax_az.setFocusCycleRoot(true);
        txt_fax_az.setName("txt_fax_az"); // NOI18N
        txt_fax_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fax_azActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout faxAzLayout = new javax.swing.GroupLayout(faxAz);
        faxAz.setLayout(faxAzLayout);
        faxAzLayout.setHorizontalGroup(
            faxAzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, faxAzLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_fax_az, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        faxAzLayout.setVerticalGroup(
            faxAzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(faxAzLayout.createSequentialGroup()
                .addComponent(txt_fax_az, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        IndirizzoAz.setBorder(javax.swing.BorderFactory.createTitledBorder("Indirizzo"));
        IndirizzoAz.setName("IndirizzoAz"); // NOI18N

        txt_ind_az.setFocusCycleRoot(true);
        txt_ind_az.setName("txt_ind_az"); // NOI18N
        txt_ind_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ind_azActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IndirizzoAzLayout = new javax.swing.GroupLayout(IndirizzoAz);
        IndirizzoAz.setLayout(IndirizzoAzLayout);
        IndirizzoAzLayout.setHorizontalGroup(
            IndirizzoAzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IndirizzoAzLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(txt_ind_az, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        IndirizzoAzLayout.setVerticalGroup(
            IndirizzoAzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndirizzoAzLayout.createSequentialGroup()
                .addComponent(txt_ind_az, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pivaAz.setBorder(javax.swing.BorderFactory.createTitledBorder("PIVA"));
        pivaAz.setName("pivaAz"); // NOI18N

        txt_piva_az.setFocusCycleRoot(true);
        txt_piva_az.setName("txt_piva_az"); // NOI18N
        txt_piva_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_piva_azActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pivaAzLayout = new javax.swing.GroupLayout(pivaAz);
        pivaAz.setLayout(pivaAzLayout);
        pivaAzLayout.setHorizontalGroup(
            pivaAzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pivaAzLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(txt_piva_az, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pivaAzLayout.setVerticalGroup(
            pivaAzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pivaAzLayout.createSequentialGroup()
                .addComponent(txt_piva_az, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        note8.setBorder(javax.swing.BorderFactory.createTitledBorder("Ragione Sociale"));
        note8.setName("note8"); // NOI18N

        txt_ragsoc_az.setFocusCycleRoot(true);
        txt_ragsoc_az.setName("txt_ragsoc_az"); // NOI18N
        txt_ragsoc_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ragsoc_azActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout note8Layout = new javax.swing.GroupLayout(note8);
        note8.setLayout(note8Layout);
        note8Layout.setHorizontalGroup(
            note8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, note8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_ragsoc_az, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        note8Layout.setVerticalGroup(
            note8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(note8Layout.createSequentialGroup()
                .addComponent(txt_ragsoc_az, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        note9.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));
        note9.setName("note9"); // NOI18N

        txt_tel_az.setFocusCycleRoot(true);
        txt_tel_az.setName("txt_tel_az"); // NOI18N
        txt_tel_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tel_azActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout note9Layout = new javax.swing.GroupLayout(note9);
        note9.setLayout(note9Layout);
        note9Layout.setHorizontalGroup(
            note9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, note9Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(txt_tel_az, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        note9Layout.setVerticalGroup(
            note9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(note9Layout.createSequentialGroup()
                .addComponent(txt_tel_az, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nazioneAz.setBorder(javax.swing.BorderFactory.createTitledBorder("Nazione"));
        nazioneAz.setName("nazioneAz"); // NOI18N

        txt_naz_az.setFocusCycleRoot(true);
        txt_naz_az.setName("txt_naz_az"); // NOI18N
        txt_naz_az.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_naz_azActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nazioneAzLayout = new javax.swing.GroupLayout(nazioneAz);
        nazioneAz.setLayout(nazioneAzLayout);
        nazioneAzLayout.setHorizontalGroup(
            nazioneAzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nazioneAzLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_naz_az, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        nazioneAzLayout.setVerticalGroup(
            nazioneAzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nazioneAzLayout.createSequentialGroup()
                .addComponent(txt_naz_az, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonSalva1.setName("buttonSalva1"); // NOI18N
        buttonSalva1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalva1ActionPerformed(evt);
            }
        });

        buttonAnnulla1.setName("buttonAnnulla1"); // NOI18N
        buttonAnnulla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnnulla1ActionPerformed(evt);
            }
        });

        jXLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jXLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jXLabel3.setText("Info Azienda");
        jXLabel3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jXLabel3.setName("jXLabel3"); // NOI18N

        IndirizzoAz1.setBorder(javax.swing.BorderFactory.createTitledBorder("Indirizzo"));
        IndirizzoAz1.setName("IndirizzoAz1"); // NOI18N

        txt_ind.setFocusCycleRoot(true);
        txt_ind.setName("txt_ind"); // NOI18N
        txt_ind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_indActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IndirizzoAz1Layout = new javax.swing.GroupLayout(IndirizzoAz1);
        IndirizzoAz1.setLayout(IndirizzoAz1Layout);
        IndirizzoAz1Layout.setHorizontalGroup(
            IndirizzoAz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IndirizzoAz1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_ind, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        IndirizzoAz1Layout.setVerticalGroup(
            IndirizzoAz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndirizzoAz1Layout.createSequentialGroup()
                .addComponent(txt_ind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nazioneAz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(faxAz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(note8, 0, 163, Short.MAX_VALUE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cittaAzienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IndirizzoAz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pivaAz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(note9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmailAzienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(1, 1, 1)
                        .addComponent(buttonSalva1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAnnulla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(provincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(citta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IndirizzoAz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cognome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(citta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IndirizzoAz1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailAzienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cittaAzienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(note8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(note9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAnnulla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSalva1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nazioneAz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IndirizzoAz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(faxAz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pivaAz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nome.getAccessibleContext().setAccessibleParent(nome);

        jXLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jXLabel2.setText("Installazione");
        jXLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jXLabel2.setName("jXLabel2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(610, 610, 610))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_nomeActionPerformed

    private void txt_cognActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cognActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_cognActionPerformed

    private void txt_citActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_citActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_citActionPerformed

    private void txt_provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_provActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_provActionPerformed

    private void txt_capActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_capActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_capActionPerformed

    private void txt_codfiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codfiscActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_codfiscActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_emailActionPerformed

    private void txt_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwdActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_pwdActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_telActionPerformed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_userActionPerformed


    private void txt_cit_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cit_azActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_cit_azActionPerformed

    private void txt_mail_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mail_azActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_mail_azActionPerformed

    private void txt_fax_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fax_azActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_fax_azActionPerformed

    private void txt_ind_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ind_azActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_ind_azActionPerformed

    private void txt_naz_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_naz_azActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_naz_azActionPerformed

    private void txt_piva_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_piva_azActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_piva_azActionPerformed

    private void txt_ragsoc_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ragsoc_azActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_ragsoc_azActionPerformed

    private void txt_tel_azActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tel_azActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_tel_azActionPerformed

    private void buttonSalva1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalva1ActionPerformed
        AppInit operazione= new AppInit();
        try {
            operazione.inserimento(amm);
            JOptionPane.showMessageDialog(null, "Operazione effettuata con successo!! Il software verrà chiuso. Riavviare per iniziare ad usarlo!");
            System.exit(0);

        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Errore dal database"+ ex.getMessage() + " " + ex.getErrorCode());
            JOptionPane.showMessageDialog(null, "Errore dal database");
        } catch (ValidatorException ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_buttonSalva1ActionPerformed

    private void buttonAnnulla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnnulla1ActionPerformed
        JOptionPane.showMessageDialog(null, "operazione annulata");
        System.exit(0);
        //editabile(false);
    }//GEN-LAST:event_buttonAnnulla1ActionPerformed

    private void txt_indActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_indActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txt_indActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cognome;
    private javax.swing.JPanel EmailAzienda;
    private javax.swing.JPanel IndirizzoAz;
    private javax.swing.JPanel IndirizzoAz1;
    private it.seerp.Gui.Gestione.BottoniGenerici.ButtonAnnulla buttonAnnulla1;
    private it.seerp.Gui.Gestione.BottoniGenerici.ButtonSalva buttonSalva1;
    private javax.swing.JPanel cap;
    private javax.swing.JPanel cf;
    private javax.swing.JPanel citta;
    private javax.swing.JPanel cittaAzienda;
    private javax.swing.JPanel email;
    private javax.swing.JPanel faxAz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private javax.swing.JPanel nazioneAz;
    private javax.swing.JPanel nome;
    private javax.swing.JPanel note8;
    private javax.swing.JPanel note9;
    private javax.swing.JPanel password;
    private javax.swing.JPanel pivaAz;
    private javax.swing.JPanel provincia;
    private javax.swing.JPanel telefono;
    private javax.swing.JTextField txt_cap;
    private javax.swing.JTextField txt_cit;
    private javax.swing.JTextField txt_cit_az;
    private javax.swing.JTextField txt_codfisc;
    private javax.swing.JTextField txt_cogn;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fax_az;
    private javax.swing.JTextField txt_ind;
    private javax.swing.JTextField txt_ind_az;
    private javax.swing.JTextField txt_mail_az;
    private javax.swing.JTextField txt_naz_az;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextArea txt_note;
    private javax.swing.JTextField txt_piva_az;
    private javax.swing.JTextField txt_prov;
    private javax.swing.JTextField txt_pwd;
    private javax.swing.JTextField txt_ragsoc_az;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_tel_az;
    private javax.swing.JTextField txt_user;
    private javax.swing.JPanel username;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param e
     */
    public void actionPerformed(ActionEvent e) {
        CommandInterface cmd = (CommandInterface) e.getSource();
        cmd.execute();

    }
}
